// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2OG648Y0SXzKGlabefchpj7NKlsqHmBY',
    appId: '1:780684725054:web:797bfff6d3b18ff4847a6f',
    messagingSenderId: '780684725054',
    projectId: 'counter-app-54105',
    authDomain: 'counter-app-54105.firebaseapp.com',
    storageBucket: 'counter-app-54105.firebasestorage.app',
    measurementId: 'G-511HDWVYJD',
    databaseURL:
        "https://counter-app-54105-default-rtdb.asia-southeast1.firebasedatabase.app/",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9CkOpfZRQdpqkk7XJpxGuhW3WyV__mqQ',
    appId: '1:780684725054:android:e6cb04fa437ec4e4847a6f',
    messagingSenderId: '780684725054',
    projectId: 'counter-app-54105',
    storageBucket: 'counter-app-54105.firebasestorage.app',
    databaseURL:
        "https://counter-app-54105-default-rtdb.asia-southeast1.firebasedatabase.app/",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs74pYJlmeuCL3UbL03A6_ER_6rcA514U',
    appId: '1:780684725054:ios:606e838178bc1e07847a6f',
    messagingSenderId: '780684725054',
    projectId: 'counter-app-54105',
    storageBucket: 'counter-app-54105.firebasestorage.app',
    iosBundleId: 'com.example.counterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs74pYJlmeuCL3UbL03A6_ER_6rcA514U',
    appId: '1:780684725054:ios:606e838178bc1e07847a6f',
    messagingSenderId: '780684725054',
    projectId: 'counter-app-54105',
    storageBucket: 'counter-app-54105.firebasestorage.app',
    iosBundleId: 'com.example.counterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2OG648Y0SXzKGlabefchpj7NKlsqHmBY',
    appId: '1:780684725054:web:efc2ed79929b8737847a6f',
    messagingSenderId: '780684725054',
    projectId: 'counter-app-54105',
    authDomain: 'counter-app-54105.firebaseapp.com',
    storageBucket: 'counter-app-54105.firebasestorage.app',
    measurementId: 'G-386ZGJX5N6',
    databaseURL:
        "https://counter-app-54105-default-rtdb.asia-southeast1.firebasedatabase.app/",
  );
}
